// <auto-generated />
namespace Swiftie.Server.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_relation_to_user_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_relation_to_user_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "201607061838151_added_relation_to_user_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
